#camunda.bpm:
#  metrics.enabled: false
#  history-level: auto
#  database:
#    schema-update: true
#    type: mysql
#
#spring.datasource:
#  url: jdbc:mysql://localhost:3306/camunda?useSSL=false
#  username: camunda
#  password: camunda
#  driver-class-name: com.mysql.jdbc.Driver
#
#server:
#  port: 8081

#dmn决策资源路径 todo save to redis
logviewer.path: /Users/moyong/project/env-rule/dmn-rest/src/main/resources/dmn

spring.datasource.testOnBorrow: true
spring.datasource.validationQuery: SELECT 1


